### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by artii252** [OlafHaalstra/Lightroom-Auto-Import-Export#2]
For some Reason I get an Error stating
An internal error has occured:[ string "ExportMEnuItem.lua"]96: attempt to index upvalue 'folder'(a nil value)

As well before I got this error it didnt seem to work for me. I would see it say Processing but no image jpg showed in the output folder

**Comment by OlafHaalstra** [comment]
Does your output folder already exists? It doesn't create it. Can you show me a screenshot of how you configured the menu?

**Comment by J404ck** [comment]
Hi! I'm facing the same problem he was.... The drop down menu also seems to be bugged. Any Idea?
![8336548b79a2f5abbbe3b11a1e0db978](https://github.com/OlafHaalstra/Lightroom-Auto-Import-Export/assets/163465868/ddfe6ff1-b89d-4d8d-8d0f-23a8c60f27e0)

**Comment by OlafHaalstra** [comment]
For some reason it looks like if you first update the "Output folder" field and then the "Select folder" this issue arises. Can you try to first select the Lightroom folder (with "Select folder") and then change the value for "Output folder".

Do you still get the issue then? I'll try to think of a fix if this also solves the problem for you.
