### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by anoril1979** [OlafHaalstra/Lightroom-Auto-Import-Export#3]
Hi!

I suppose my problem comes from an incompatibility issue but you may help if it is not the case.

I installed the plugin as described in the guide, but LR (6.14) tells me the plugin cannot be loaded: "In Info.lua file, VERSION.build was of type string; number was expected."

I'm stuck here :)

Regards

**Comment by OlafHaalstra** [comment]
Can you try again with the latest changes? I think I addressed the issue.

**Comment by anoril1979** [comment]
Hi! Thanks! That's great and working smoothly now! <3
