### ISSUE TITLE
[Wishlist] Predefined Export settings

### ISSUE THREAD

**Issue by anoril1979** [OlafHaalstra/Lightroom-Auto-Import-Export#5]
Hi!

Because I work on shooting during convention, your plugin is very valuable as it automates my presets and export. BUT I'm used to having specific params to my export (constraints, borders, filigrans, metadata and copyrights).

Is it possible to automatically use a specific export setting (according to its name or with a dropdown box in the plugin window)?

I would greatly enjoy that!

**Comment by OlafHaalstra** [comment]
@anoril1979 I've added the option to select a 'lrtemplate' file and that will copy the settings and apply it to your export. Since I don't regularly use these files could you test and see if this works correctly for you? You can take the code from #8

**Comment by anoril1979** [comment]
Great! I try this ASAP.

Regards

**Comment by anoril1979** [comment]
Hi!
It does seem to work. :/

Basic export settings like Resizing is not applied, as for the watermark that is not applied.
Here is an export preset I used for my testings.

Preset:
`s = {
	id = "BBC65DF3-38A7-4718-880A-1DBA013CE34D",
	internalName = "Yggdrasil 2024",
	title = "Yggdrasil 2024",
	type = "Export",
	value = {
		collisionHandling = "overwrite",
		embeddedMetadataOption = "all",
		exportServiceProvider = "com.adobe.ag.export.file",
		exportServiceProviderTitle = "Disque dur",
		export_colorSpace = "sRGB",
		export_destinationPathSuffix = "Export - Yggdrasil 2024-2",
		export_destinationType = "pictures",
		export_postProcessing = "revealInFinder",
		export_useSubfolder = true,
		export_videoFileHandling = "include",
		export_videoFormat = "4e49434b-4832-3634-fbfb-fbfbfbfbfbfb",
		export_videoPreset = "original",
		extensionCase = "lowercase",
		format = "JPEG",
		includeFaceTagsAsKeywords = false,
		includeFaceTagsInIptc = false,
		includeVideoFiles = true,
		initialSequenceNumber = 1,
		jpeg_limitSize = 100,
		jpeg_quality = 1,
		jpeg_useLimitSize = false,
		metadata_keywordOptions = "flat",
		outputSharpeningLevel = 1,
		outputSharpeningMedia = "glossy",
		outputSharpeningOn = true,
		reimportExportedPhoto = false,
		reimport_stackWithOriginal = false,
		reimport_stackWithOriginal_position = "below",
		removeFaceMetadata = true,
		removeLocationMetadata = true,
		renamingTokensOn = false,
		selectedTextFontFamily = "Myriad Web Pro",
		selectedTextFontSize = 12,
		size_doConstrain = true,
		size_doNotEnlarge = false,
		size_maxHeight = 800,
		size_maxWidth = 800,
		size_percentage = 100,
		size_resizeType = "wh",
		size_resolution = 240,
		size_resolutionUnits = "inch",
		size_units = "pixels",
		size_userWantsConstrain = true,
		tokenCustomString = "01 - Album Mamies",
		tokens = "{{custom_token}}-{{naming_sequenceNumber_1Digit}}",
		tokensArchivedToString2 = "{{custom_token}}-{{naming_sequenceNumber_1Digit}}",
		useWatermark = true,
		watermarking_id = "550D049C-CFC7-4310-AE8E-2E9EFD58BB8F",
	},
	version = 0,
}
`

And here is the watermark file:
`
s = {
	id = "550D049C-CFC7-4310-AE8E-2E9EFD58BB8F",
	internalName = "Elegant Weapons",
	title = "Elegant Weapons",
	type = "WatermarkingPreset",
	value = {
		items = {
			{
				anchor = "bottomleft",
				horizontalPadding = 0.001,
				imagePath = "E:\\Documents\\Projects\\SaberBuilder\\SaberSmith\\EW\\Divers\\Police de Caractères\\EW_LOGO_NB_CARRE_MARK.png",
				kind = "image",
				opacity = 1,
				orientation = "AB",
				sizeKind = "relative",
				sizeRelativeAmount = 0.15,
				text = "Copyright",
				textColorBlue = 1,
				textColorGreen = 1,
				textColorRed = 1,
				textFontName = "Myriad Web Pro-Regular",
				textHorizontalAlignment = "left",
				textShadowAngle = 270,
				textShadowEnabled = true,
				textShadowOffset = 0.1,
				textShadowOpacity = 0.8,
				textShadowRadius = 0.2,
				textVerticalAlignment = "top",
				verticalPadding = 0.014,
			},
		},
	},
	version = 0,
}
`

(If you copy-paste this to your LR folders, you would change the imagePath to point to a test image from yours.)

I would enjoy to help you further as it is a great and important feature to me, but I have to LR coding knowledge. :/

Thanks for your involvment!
Paul

**Comment by picturelab** [comment]
Is there anything that can export and auto watermark?

**Comment by anoril1979** [comment]
Hi @picturelab !
This is what I expect, having the predefined Export Settings used. But there are some issues for now.

**Comment by OlafHaalstra** [comment]
Hi @anoril1979, 

The problem should be fixed now, please checkout the code with #8 and let me know if everything works as expected

**Comment by anoril1979** [comment]
I try it right now!

**Comment by anoril1979** [comment]
It is working like a charm! Congrats and many thanks!
A note BTW: your UI ask for a preset and a folder where to export, but when the export settings present an export folder, it overrides the UI folder chosen. Not an issue actually.

Many thanks for this incredible usefull plugin!
