### ISSUE TITLE
[Wishlist] Printer instead of Export

### ISSUE THREAD

**Issue by anoril1979** [OlafHaalstra/Lightroom-Auto-Import-Export#6]
Hi!

Because I work on shooting during convention, auto-exportation is very valuble BUT as I also make prints for the visitors I shoot.

Is it possible to redirect the exportation to the printer instead (or "also")?

I would greatly enjoy that (too)! :)

**Comment by OlafHaalstra** [comment]
Hi @anoril1979,

Thanks for your suggestion.

Printing looks like a whole different game in LR, it doesn't fully fit the functionality of the script and there are no easy APIs to work with.

For now I'll close this issue.
