### ISSUE TITLE
[Wishlist] Why put up a flag?

### ISSUE THREAD

**Issue by xulioiglesias** [OlafHaalstra/Lightroom-Auto-Import-Export#7]
Hi! I use this procedure:
1. I run your plugin "every 60 seconds"
2. I start automatic import to lightroom from the camera so that photos are uploaded immediately to lightroom
Problem: Nothing happens because the photos are not flagged. Therefore, you need to go in and mark the photo with a flag and then the plugin will start working. Is it possible to make it so that you don't have to mark the photo with a flag?

The desired scenario:
1. I run your plugin "every 60 seconds"
2. I start automatic import to lightroom from the camera so that photos are uploaded immediately to lightroom
3. Your plugin works out and the photo is immediately exported

Thanks you!

**Comment by OlafHaalstra** [comment]
@xulioiglesias  I've added an option to not be required to use a flag. Could you try and see if this works correctly for you by taking the code from #8
